server:
  port: 8080

spring:
  thymeleaf:
    cache: false
  datasource:
    url: jdbc:mysql://localhost:3306/practise?createDatabaseIfNotExist=true&autoReconnect=true&allowPublicKeyRetrieval=true&useSSL=false
    username: root
    password: Danieldd11
    platform: mysql
    initialization-mode: always
    data: classpath:db/*.sql
  jpa:
    #show or not log for each query
    show-sql: on
    generate-ddl: on
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
        format_sql: on
        use_sql_comments: on
