server:
  port: 8081

spring:
  thymeleaf:
    cache: off
  jpa:
    #show or not log for each query
    show-sql: on
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
  datasource:
    url: jdbc:mysql://localhost:3306/practise
    username: root
    password: Danieldd11
    driver-class-name: com.mysql.jdbc.Driver
    dbcp2:
      # Keep the connection alive if idle for a long time
      test-while-idle: true
      validationQuery: SELECT 1

