debug: off

server:
  port: 8080
  error:
    include-exception: on
    include-stacktrace: on_param

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/practise?createDatabaseIfNotExist=true&autoReconnect=true&useSSL=false
    username: root
    password: Danieldd11
    driver-class-name: com.mysql.cj.jdbc.Driver
    platform: mysql
    initialization-mode: always
    data: classpath:db/*.sql
  jpa:
    #show or not log for each query
    show-sql: on
    generate-ddl: on
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
        format_sql: on
        use_sql_comments: on
  thymeleaf:
    cache: false

logging:
  level:
    org.hibernate.type: trace
